urls.py
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from blog_chanoir2303 import settings
from . import views

app_name = 'blog'
urlpatterns = [
    path('news', views.NewsView.as_view(), name='news'),
    path('tutorials/', views.TutorialView.as_view(), name='tutorials'),
    path('archives/', views.ArchiveView.as_view(), name='archives'),
    path('formAdmin/', views.formAdmin, name='formAdmin'),
    path('login/', LoginView.as_view(template_name='blog/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(template_name='blog/logout.html', next_page='blog:news'), name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
from django.db import models
from django.utils import timezone


class Article(models.Model):
    title = models.CharField(max_length=40)
    pub_date = models.DateTimeField(default=timezone.now())
    author = models.CharField(default='Admin', max_length=40)
    previewed_text = models.CharField(default='none', max_length=400)
    file = models.FileField(upload_to='article_file', null=True)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Tutorial(models.Model):
    title = models.CharField(max_length=40)
    pub_date = models.DateTimeField(default=timezone.now())
    author = models.CharField(default='Admin', max_length=40)
    previewed_text = models.CharField(default='none', max_length=400)
    file = models.FileField(upload_to='tutorial_file', null=True)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Feedback(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    feedback_text = models.TextField()

    def __str__(self):
        return self.feedback_text


class Link(models.Model):
    title = models.CharField(max_length=40)
    link = models.CharField(max_length=500)

    def __str__(self):
        return self.title

views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views import generic

from .models import Article, Tutorial
from .templates.blog.form import ArticleForm, TutorialForm


class NewsView(generic.ListView):
    template_name = 'blog/news.html'
    context_object_name = 'latest_article_list'

    def get_queryset(self):
        """Return the last 6 published article_file"""
        return Article.objects.order_by('-pub_date')[:6]


class TutorialView(generic.ListView):
    template_name = 'blog/tutorials.html'
    context_object_name = 'latest_tutorial_list'

    def get_queryset(self):
        """Return tutorial list"""
        return Tutorial.objects.order_by('-pub_date')


class ArchiveView(generic.ListView):
    template_name = 'blog/archives.html'
    context_object_name = 'archive_list'

    def get_queryset(self):
        return Article.objects.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super(ArchiveView, self).get_context_data(**kwargs)
        context['article'] = Article.objects.all().order_by('-pub_date')
        context['tutorial'] = Tutorial.objects.all().order_by('-pub_date')
        context['all'] = list(context['article']) + list(context['tutorial'])
        return context


@login_required
def formAdmin(request):
    form_article = ArticleForm()
    if request.method == 'POST':
        print(request.POST)
        form_article = ArticleForm(request.POST, request.FILES)
        if form_article.is_valid():
            form_article.save()

    context = {
        'form_article': form_article,
    }
    return render(request, 'blog/form.html', context)

templates/blog/archives.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CHANOIR Archives</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<header>
    <div id="header-title">
        <h2>Archives</h2>
    </div>
</header>
<section id="main-section">
    <section id="left-section">
        <div id="search-bar">
            <span class="material-icons-outlined icon-input-search">search</span><label for="input-search-bar"></label>
            <input type="text" id="input-search-bar" placeholder="Search">
        </div>
        <div id="category">
            <div id="blog-category">
                <h6>Blog</h6>
                <a href="{% url 'blog:news' %}" class="blog-category-item"><span class="material-icons-outlined white-icon-category-item">newspaper</span>&nbsp;&nbsp;News</a>
                <a href="{% url 'blog:tutorials' %}" class="blog-category-item"><span class="material-icons-outlined white-icon-category-item">library_books</span>&nbsp;&nbsp;Tutorials</a>
                <a href="{% url 'blog:archives' %}" class="blog-category-item"><span class="material-icons-outlined white-icon-category-item">move_to_inbox</span>&nbsp;&nbsp;Archives</a>
            </div>
            <div id="library-category">
                <h6>Library</h6>
                <a href="https://github.com/chanoir2303" class="library-category-item"><span class="material-icons-outlined white-icon-category-item">code</span>&nbsp;&nbsp;Github</a>
                <a href="#" class="library-category-item"><span class="material-icons-outlined white-icon-category-item">collections_bookmark</span>&nbsp;&nbsp;Portfolio</a>
                <a href="#" class="library-category-item"><span class="material-icons-outlined white-icon-category-item">photo_camera</span>&nbsp;&nbsp;Photographs</a>
            </div>
            <div id="production-category">
                <h6>Production</h6>
                <a href="#" class="production-category-item"><span class="material-icons-outlined grey-icon-category-item">link</span>&nbsp;&nbsp;Pickapass</a>
                <a href="#" class="production-category-item"><span class="material-icons-outlined grey-icon-category-item">link</span>&nbsp;&nbsp;QR loyalty</a>
            </div>
        </div>
    </section>
    <section id="right-section">
        <div id="article-list">
            {% for latest_article in all %}
            <div class="article-item">
                <span class="article-item-title">{{ latest_article.title }}</span>
                <div class="article-item-previewed-text">{{ latest_article.previewed_text }}</div>
                <div class="article-item-form">
                    <form action="{{latest_article.file}}">
                        <button type="submit" class="article-item-button-more">Read more</button>
                    </form>
                </div>
                <div class="article-item-infos">
                    <span class="article-item-date">{{ latest_article.pub_date }}</span>
                    <div>
                        <span class="material-icons-outlined icon-article-item-vote">visibility</span>
                        <span>{{ latest_article.vote }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </section>
</section>
</body>
<footer></footer>
</html>

templates/blog/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Push Form</title>
</head>
<body>
<div>
    <h2>Article</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form_article }}
        <input type="submit" value="post"/>
    </form>
</div>
</body>
</html>

templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
</body>
</html>

templates/blog/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CHANOIR News</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<header>
    <div id="header-title">
        <h2>News</h2>
    </div>
</header>
<section id="main-section">
    <section id="left-section">
        <div id="search-bar">
            <span class="material-icons-outlined icon-input-search">search</span><label for="input-search-bar"></label>
            <input type="text" id="input-search-bar" placeholder="Search">
        </div>
        <div id="category">
            <div id="blog-category">
                <h6>Blog</h6>
                <a href="{% url 'blog:news' %}" class="blog-category-item"><span class="material-icons-outlined light-icon-category-item">newspaper</span>&nbsp;&nbsp;News</a>
                <a href="{% url 'blog:tutorials' %}" class="blog-category-item"><span class="material-icons-outlined light-icon-category-item">library_books</span>&nbsp;&nbsp;Tutorials</a>
                <a href="{% url 'blog:archives' %}" class="blog-category-item"><span class="material-icons-outlined light-icon-category-item">move_to_inbox</span>&nbsp;&nbsp;Archives</a>
            </div>
            <div id="library-category">
                <h6>Library</h6>
                <a href="https://github.com/chanoir2303" class="library-category-item"><span class="material-icons-outlined light-icon-category-item">code</span>&nbsp;&nbsp;Github</a>
                <a href="#" class="library-category-item"><span class="material-icons-outlined light-icon-category-item">collections_bookmark</span>&nbsp;&nbsp;Portfolio</a>
                <a href="#" class="library-category-item"><span class="material-icons-outlined light-icon-category-item">photo_camera</span>&nbsp;&nbsp;Photographs</a>
            </div>
            <div id="production-category">
                <h6>Production</h6>
                <a href="#" class="production-category-item"><span class="material-icons-outlined dark-icon-category-item">link</span>&nbsp;&nbsp;Pickapass</a>
                <a href="#" class="production-category-item"><span class="material-icons-outlined dark-icon-category-item">link</span>&nbsp;&nbsp;QR loyalty</a>
            </div>
        </div>
    </section>
     <section id="right-section">
        <div id="article-list">
            {% for latest_article in latest_article_list %}
            <div class="article-item">
                <span class="article-item-title">{{ latest_article.title }}</span>
                <div class="article-item-previewed-text">{{ latest_article.previewed_text }}</div>
                {% if latest_article.file %}
                <div class="article-item-form">
                    <form action="{{latest_article.file.url}}">
                        <button type="submit" class="article-item-button-more">Read more</button>
                    </form>
                </div>
                {% else %}
                <div class="article-item-form">
                    <form action="">
                        <button type="submit" class="article-item-button-more">Soon</button>
                    </form>
                </div>
                {% endif %}
                <div class="article-item-infos">
                    <span class="article-item-date">{{ latest_article.pub_date }}</span>
                    <div>
                        <span class="material-icons-outlined icon-article-item-vote">visibility</span>
                        <span class="article-item-vote-counter">{{ latest_article.vote }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        <form action="{% url 'blog:archives' %}" id="view-all-form">
            <button type="submit" id="view-all-button">View all articles</button>
        </form>
    </section>
</section>
</body>
<footer></footer>
</html>

templates/blog/tutorials.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CHANOIR Tutorials</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<header>
    <div id="header-title">
        <h2>Tutorials</h2>
    </div>
</header>
<section id="main-section">
    <section id="left-section">
        <div id="search-bar">
            <span class="material-icons-outlined icon-input-search">search</span><label for="input-search-bar"></label>
            <input type="text" id="input-search-bar" placeholder="Search">
        </div>
        <div id="category">
            <div id="blog-category">
                <h6>Blog</h6>
                <a href="{% url 'blog:news' %}" class="blog-category-item"><span class="material-icons-outlined white-icon-category-item">newspaper</span>&nbsp;&nbsp;News</a>
                <a href="{% url 'blog:tutorials' %}" class="blog-category-item"><span class="material-icons-outlined white-icon-category-item">library_books</span>&nbsp;&nbsp;Tutorials</a>
                <a href="{% url 'blog:archives' %}" class="blog-category-item"><span class="material-icons-outlined white-icon-category-item">move_to_inbox</span>&nbsp;&nbsp;Archives</a>
            </div>
            <div id="library-category">
                <h6>Library</h6>
                <a href="https://github.com/chanoir2303" class="library-category-item"><span class="material-icons-outlined white-icon-category-item">code</span>&nbsp;&nbsp;Github</a>
                <a href="#" class="library-category-item"><span class="material-icons-outlined white-icon-category-item">collections_bookmark</span>&nbsp;&nbsp;Portfolio</a>
                <a href="#" class="library-category-item"><span class="material-icons-outlined white-icon-category-item">photo_camera</span>&nbsp;&nbsp;Photographs</a>
            </div>
            <div id="production-category">
                <h6>Production</h6>
                <a href="#" class="production-category-item"><span class="material-icons-outlined grey-icon-category-item">link</span>&nbsp;&nbsp;Pickapass</a>
                <a href="#" class="production-category-item"><span class="material-icons-outlined grey-icon-category-item">link</span>&nbsp;&nbsp;QR loyalty</a>
            </div>
        </div>
    </section>
     <section id="right-section">
        <div id="article-list">
            {% for latest_tutorial in latest_tutorial_list %}
            <div class="article-item">
                <span class="article-item-title">{{ latest_tutorial.title }}</span>
                <div class="article-item-previewed-text">{{ latest_tutorial.previewed_text }}</div>
                {% if latest_tutorial.file %}
                <div class="article-item-form">
                    <form action="{{latest_tutorial.file.url}}">
                        <button type="submit" class="article-item-button-more">Read more</button>
                    </form>
                </div>
                {% else %}
                <div class="article-item-form">
                    <form action="">
                        <button type="submit" class="article-item-button-more">Soon</button>
                    </form>
                </div>
                {% endif %}
                <div class="article-item-infos">
                    <span class="article-item-date">{{ latest_tutorial.pub_date }}</span>
                    <div>
                        <span class="material-icons-outlined icon-article-item-vote">visibility</span>
                        <span class="article-item-vote-counter">{{ latest_tutorial.vote }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </section>
</section>
</body>
<footer></footer>
</html>